require("daanmoura.plugins-setup") -- should be at the top
require("daanmoura.core.options")
require("daanmoura.core.keymaps")
require("daanmoura.core.colorscheme")
require("daanmoura.plugins.comment")
require("daanmoura.plugins.nvim-tree")
require("daanmoura.plugins.lualine")
require("daanmoura.plugins.telescope")
require("daanmoura.plugins.nvim-cmp")
require("daanmoura.plugins.lsp.mason")
require("daanmoura.plugins.lsp.lspsaga")
require("daanmoura.plugins.lsp.lspconfig")
require("daanmoura.plugins.lsp.null-ls")
require("daanmoura.plugins.autopairs")
require("daanmoura.plugins.treesitter")
require("daanmoura.plugins.gitsigns")
require("daanmoura.plugins.gitlab")
require("daanmoura.plugins.blamer")
